"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

import os
from pathlib import Path
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def parse_bool(val, default=False):
    """Parse string/bool representation into boolean."""
    if val is None:
        return default
    if isinstance(val, bool):
        return val
    return str(val).strip().lower() in ('true', '1', 'yes', 'on')


# -----------------------------------------------------------------------------
# Production & Environment Detection
# -----------------------------------------------------------------------------
# Detect production based on explicit hosting platforms or environment flags.
_is_production = (
    parse_bool(os.environ.get('RENDER'))
    or os.environ.get('DJANGO_ENV', '').lower() in ('production', 'prod')
    or os.environ.get('ENVIRONMENT', '').lower() in ('production', 'prod')
    or (os.environ.get('DJANGO_DEBUG') is not None and not parse_bool(os.environ.get('DJANGO_DEBUG'), default=True))
)

# Control whether local backend/.env should be loaded:
# - Disabled automatically in production (_is_production).
# - Can be explicitly disabled via LOAD_DOTENV=False (without altering _is_production or DEBUG).
_should_load_dotenv = (
    not _is_production
    and parse_bool(os.environ.get('LOAD_DOTENV', 'True'), default=True)
)

if _should_load_dotenv:
    _env_file = BASE_DIR / '.env'
    if _env_file.is_file():
        try:
            with open(_env_file, encoding='utf-8') as _f:
                for _line in _f:
                    _line = _line.strip()
                    if _line and not _line.startswith('#') and '=' in _line:
                        _k, _v = _line.split('=', 1)
                        os.environ.setdefault(_k.strip(), _v.strip().strip('"').strip("'"))
        except OSError:
            pass


# -----------------------------------------------------------------------------
# Security & Debug Settings
# -----------------------------------------------------------------------------

DEBUG = parse_bool(os.environ.get('DJANGO_DEBUG'), default=not _is_production)

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-local-secret-key-dailybuddy-74x2aqaiy'
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY (or SECRET_KEY) environment variable must be set in production when DEBUG is False."
        )

# Allowed hosts
allowed_hosts_raw = os.environ.get('ALLOWED_HOSTS', '')
if allowed_hosts_raw:
    ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_raw.split(',') if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
else:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS environment variable must be set in production when DEBUG is False."
    )


# -----------------------------------------------------------------------------
# Application definition
# -----------------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'core',
    'tasks',
    'reminders',
    'habits',
    'commitments',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# -----------------------------------------------------------------------------
# Database Configuration
# Defaults to SQLite locally; switches to PostgreSQL if DATABASE_URL is set
# -----------------------------------------------------------------------------

DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif not DEBUG:
    raise ImproperlyConfigured(
        "DATABASE_URL environment variable must be set in production when DEBUG is False."
    )
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# -----------------------------------------------------------------------------
# Password validation
# -----------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# -----------------------------------------------------------------------------
# Internationalization
# -----------------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# -----------------------------------------------------------------------------
# Static files (CSS, JavaScript, Images) with WhiteNoise support
# -----------------------------------------------------------------------------

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# -----------------------------------------------------------------------------
# CORS & CSRF Configuration
# -----------------------------------------------------------------------------

DEFAULT_CORS_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://localhost:5175",
    "http://127.0.0.1:5175",
]

cors_origins_raw = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if cors_origins_raw:
    CORS_ALLOWED_ORIGINS = list(
        set(
            DEFAULT_CORS_ORIGINS
            + [o.strip() for o in cors_origins_raw.split(',') if o.strip()]
        )
    )
else:
    CORS_ALLOWED_ORIGINS = DEFAULT_CORS_ORIGINS

csrf_trusted_raw = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if csrf_trusted_raw:
    CSRF_TRUSTED_ORIGINS = [
        o.strip() for o in csrf_trusted_raw.split(',') if o.strip()
    ]
elif DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]
else:
    CSRF_TRUSTED_ORIGINS = []


# -----------------------------------------------------------------------------
# Django REST Framework Configuration
# -----------------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'core.permissions.IsOwner',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '120/minute',
        'user': '1000/minute',
        'login': '15/minute',
    },
}


# -----------------------------------------------------------------------------
# Production HTTPS & Security Settings
# -----------------------------------------------------------------------------

if not DEBUG:
    # Render terminates SSL at reverse proxy and forwards X-Forwarded-Proto header
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = parse_bool(os.environ.get('SECURE_SSL_REDIRECT'), default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

    hsts_seconds = os.environ.get('SECURE_HSTS_SECONDS')
    if hsts_seconds:
        try:
            SECURE_HSTS_SECONDS = int(hsts_seconds)
            SECURE_HSTS_INCLUDE_SUBDOMAINS = parse_bool(os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS'), default=True)
            SECURE_HSTS_PRELOAD = parse_bool(os.environ.get('SECURE_HSTS_PRELOAD'), default=True)
        except ValueError:
            pass
